"""Add shared_links and slug_redirects

Revision ID: 2eba6bf6c075
Revises: 9b179edaf255
Create Date: 2026-02-24 21:43:14.108306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eba6bf6c075'
down_revision: Union[str, Sequence[str], None] = '9b179edaf255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_links_id'), 'shared_links', ['id'], unique=False)
    op.create_index(op.f('ix_shared_links_uuid'), 'shared_links', ['uuid'], unique=True)
    op.create_table('slug_redirects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_slug', sa.String(), nullable=False),
    sa.Column('new_slug', sa.String(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slug_redirects_id'), 'slug_redirects', ['id'], unique=False)
    op.create_index(op.f('ix_slug_redirects_old_slug'), 'slug_redirects', ['old_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slug_redirects_old_slug'), table_name='slug_redirects')
    op.drop_index(op.f('ix_slug_redirects_id'), table_name='slug_redirects')
    op.drop_table('slug_redirects')
    op.drop_index(op.f('ix_shared_links_uuid'), table_name='shared_links')
    op.drop_index(op.f('ix_shared_links_id'), table_name='shared_links')
    op.drop_table('shared_links')
    # ### end Alembic commands ###
